name: Deploy Firebase Hosting on merge

on:
  push:
    branches:
      - main  # Mỗi khi bạn push code lên nhánh main, nó sẽ tự deploy

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Lấy code từ GitHub
      - name: Checkout code
        uses: actions/checkout@v4

      # 2️⃣ Deploy trực tiếp lên Firebase Hosting
      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_TA_EDU_NH }}'
          channelId: live
          projectId: ta-edu-nh
